{
 "title": "Sonos - Overview",
 "tags": [
  "prometheus",
  "sonos"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ZoneName",
    "label": "Speaker",
    "query": {
     "query": "label_values(sonos_status_rxBytes, ZoneName)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(sonos_status_rxBytes{ZoneName=~\"$ZoneName\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Speakers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(sonos_status_txqueuelen) by (ZoneName)",
     "legendFormat": "{{ZoneName}}"
    }
   ]
  },
  {
   "title": "Software Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(sonos_status_txqueuelen) by (SoftwareVersion)",
     "legendFormat": "{{SoftwareVersion}}"
    }
   ]
  },
  {
   "title": "Speaker Information",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ZoneName, IPAddress, host, HardwareVersion, SerialNumber, SeriesID, SoftwareVersion) (sonos_status_txqueuelen{ZoneName=~\"$ZoneName\"})"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "irate(sonos_status_rxBytes{ZoneName=~\"$ZoneName\", interface=~\"$interface\"} [1m])*8",
     "legendFormat": "{{ZoneName}}: {{interface}}:  Inbound"
    },
    {
     "expr": "irate(sonos_status_txBytes{ZoneName=~\"$ZoneName\", interface=~\"$interface\"} [1m])*8",
     "legendFormat": "{{ZoneName}}: {{interface}}:  Outbound"
    }
   ]
  },
  {
   "title": "Packet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(sonos_status_rxPackets{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[1m])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Inbound"
    },
    {
     "expr": "irate(sonos_status_txPackets{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[1m])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Outbound"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "irate(sonos_status_rxDropped{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Inbound"
    },
    {
     "expr": "irate(sonos_status_TxDropped{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Outbound"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sonos_status_rxDropped{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[1m])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Inbound"
    },
    {
     "expr": "irate(sonos_status_TxDropped{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[1m])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Outbound"
    }
   ]
  },
  {
   "title": "Packet Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "irate(sonos_status_rxErrors{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Inbound"
    },
    {
     "expr": "irate(sonos_status_TxErrors{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Outbound"
    }
   ]
  },
  {
   "title": "Packet Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sonos_status_rxErrors{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[1m])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Inbound"
    },
    {
     "expr": "irate(sonos_status_TxErrors{ZoneName=~\"$ZoneName\", interface=~\"$interface\"}[1m])",
     "legendFormat": "{{ZoneName}}: {{interface}}: Outbound"
    }
   ]
  }
 ]
}